---
- name: cleanup
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: reverse the enabling of sudo without tty for some ansible commands
      replace:
        path: /etc/sudoers
        regexp: 'Defaults\s*!requiretty'
        replace: '^Defaults requiretty'
        backup: true

    - name: Remove the repo file
      file:
        state: absent
        path: /etc/yum.repos.d/open_three-tier-app.repo

    - name: remove base tools and three tier app packages
      yum:
        name: "{{ item }}" 
        state: absent
      with_items:
        - httpie
        - python-pip
        - haproxy
        - tomcat
        - postgresql-server

    - name: delete tomcat webapps directory - removing index.html etc
      file:
        path: /usr/share/tomcat/webapps
        state: absent

    - name: delete haproxy.cfg from /etc/haproxy
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent
